# Generated by Django 3.1.2 on 2021-10-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioquiz', '0002_auto_20211030_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='none', upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(default='none'),
            preserve_default=False,
        ),
    ]
