# Generated by Django 3.1.2 on 2021-11-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioquiz', '0004_auto_20211030_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
