# Generated by Django 3.1.2 on 2021-11-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioquiz', '0005_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='points',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='Correct_answer',
            field=models.ManyToManyField(to='Bioquiz.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='Quiz_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='id_images',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='question',
            name='imageField',
        ),
        migrations.AddField(
            model_name='question',
            name='imageField',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
