# Generated by Django 3.1.2 on 2021-11-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioquiz', '0006_auto_20211105_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='Correct_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
