# Generated by Django 3.1.2 on 2021-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioquiz', '0007_auto_20211105_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='lvl',
            field=models.IntegerField(default=0),
        ),
    ]
